spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seneca_test?autoreconnect=true
    username: root
    password: Mysql@123
    testOnBorrow: true
    hikari:
      maxLifetime: 115000
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
  
request:
  log:
    jsonBodies: true
    maxPayloadLength: 1000
    excludeUrlPatterns: '/actuator/health,/actuator/liveness,/actuator/prometheus'


server:
  tomcat:
    mbeanregistry:
      enabled: true